### PR TITLE
Create MergeKSortedList.cpp

### PR DESCRIPTION
**Pull request by JayantGoel001**

### CODE REVIEW

**Comment by JayantGoel001** [comment]
@code1511 Please Review my PR and consider merging it.

**Comment by code1511** [comment]
Okay, It's under review!
Till then can you give a star to the repo :)

**Comment by code1511** [comment]
Can you please tell me whether you are making this PR for hacktoberfest?? So that I can enable the label for it

**Comment by JayantGoel001** [comment]
> Can you please tell me whether you are making this PR for hacktoberfest?? So that I can enable the label for it

Yes it's for hacktobefest

**Review by code1511 — APPROVED** [review]

**Pull request merged**
